# REVOKE CONNECT ON DATABASE $MYSQL_DB FROM public;
# REVOKE ALL ON SCHEMA public FROM public;

# CREATE USER $MYSQL_APP_USER WITH PASSWORD $MYSQL_APP_PASSWORD;

# CREATE SCHEMA drizzle;

# GRANT ALL ON DATABASE $MYSQL_DB TO $MYSQL_APP_USER;
# GRANT ALL ON SCHEMA public TO $MYSQL_APP_USER;
# GRANT ALL ON SCHEMA drizzle TO p$MYSQL_APP_USER;
