name: PJT

services:
  mysql:
    image: mysql:8.0
    container_name: PJT-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"   # ถ้าไม่จำเป็นให้เปิดข้างนอก ตัดบรรทัดนี้ได้
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - PJT-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PJT-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql             # ใช้ชื่อ service ของ MySQL
      BACKEND_PORT: ${BACKEND_PORT}
      NODE_ENV: ${NODE_ENV:-production}
      DEBUG: pf-backend
    ports:
      - "${BACKEND_PORT:-5002}:5002"
    networks:
      - PJT-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5002/health || exit 1"]
      interval: 10s
      timeout: 4s
      retries: 6

volumes:
  mysql-data:

networks:
  PJT-net:
    driver: bridge   # ← เปลี่ยนจาก driver: bridge เป็น external: true
